<?xml version="1.0"?>
<package format="3">
  <name>robot3_movements</name>
  <version>0.0.1</version>
  <description>Movement command publisher for Robot 1 and Robot 2</description>

  <maintainer email="chandan@example.com">chandan</maintainer>
  <license>Apache-2.0</license>

  <!-- Build system -->
  <buildtool_depend>ament_python</buildtool_depend>

  <!-- Runtime dependencies -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <!-- Testing (optional) -->
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>
